version: "3.8"

services:
  postgres-auth:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
  auth:
    build:
      context: ./apps/auth
    ports:
      - "3000:3000"
    environment:
      - PORT=${AUTH_PORT}
      - JWT_SECRET=${AUTH_JWT_SECRET}
      - DATABASE_URL=${AUTH_DATABASE_URL}
    depends_on:
      - postgres-auth
    command: sh -c "npm run wait-for-db && npm run start:prod"
  orders:
    build:
      context: ./apps/orders
    ports:
      - "3001:3001"
    environment:
      - PORT=${ORDERS_PORT}
volumes:
  postgres_auth_data: