version: "3.8"

services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "lTuBTo6dRsmhZsMctCsS-A"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
    labels:
      - "traefik.enable=false"
  init-kafka:
    image: confluentinc/cp-kafka:latest
    labels:
      - "traefik.enable=false"
    depends_on:
      - kafka
    command: >
      /bin/bash -c "/usr/bin/kafka-topics --create --bootstrap-server kafka:29092 --topic user-events --partitions 1 --replication-factor 1 --if-not-exists"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  scraper:
    build: ./apps/scraper
    environment:
      KAFKA_BROKER: kafka:29092
      SCRAPER_TIMEOUT: ${SCRAPER_TIMEOUT}
      USER_AGENT: ${USER_AGENT}
    labels:
      - "traefik.enable=false"
    depends_on:
      - kafka
  email:
    build: ./apps/email
    environment:
      KAFKA_BROKER: kafka:29092
      REDIS_URL: redis://redis:6379
      EMAIL_HOST: ${SMTP_HOST}
      EMAIL_PORT: ${SMTP_PORT}
      EMAIL_USER: ${SMTP_USER}
      EMAIL_APP_PASSWORD: ${SMTP_PASSWORD}
    labels:
      - "traefik.enable=false"
    depends_on:
      - kafka
      - redis
    command: sh -c "npm run wait-for-kafka && npm run start:prod"
  postgres-auth:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_DATABASE_URL: ${AUTH_DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
  auth:
    build:
      context: ./apps/auth
    environment:
      PORT: ${AUTH_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${AUTH_DATABASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost.auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
    depends_on:
      - postgres-auth
    command: sh -c "npm run wait-for-db && npm run start:prod"
  postgres-orders:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${ORDERS_DB_USER}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASSWORD}
      POSTGRES_DB: ${ORDERS_DB_NAME}
    ports:
      - "5433:5433"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
  orders:
    build:
      context: ./apps/orders
    ports:
      - "3001:3001"
    environment:
      PORT: ${ORDERS_PORT}
      DATABASE_URL: ${ORDERS_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`localhost.orders`)"
      - "traefik.http.services.orders.loadbalancer.server.port=3001"
    depends_on:
      - postgres-orders
    command: sh -c "npm run wait-for-db && npm run start:prod"

volumes:
  postgres_auth_data:
  postgres_orders_data: