name: Build Auth Service

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root dependencies (optional, if using workspaces)
        run: npm ci

      - name: Install auth service dependencies
        run: cd apps/auth && npm ci

      - name: Generate Prisma Client for auth
        run: cd apps/auth && npx prisma generate

      - name: Build auth service
        run: npm run build:auth

      - name: Build Auth Docker Image
        run: docker build -t auth-service ./apps/auth

      - name: Build orders service
        run: npm run build:orders

      - name: Build Orders Docker Image
        run: docker build -t orders-service ./apps/orders